Support outputting a list of databases as JSON
fermyon/cloud-plugin pull request #112
Opened 2023-10-02 21:23 UTC by kate-goldenring

Takes a similar approach as `spin templates list` and provides an option of listing databases as JSON

Example output:

```sh
[
  {
    "database": "brilliant-kangaroo",
    "links": [
      {
        "label": "default",
        "app": "todo"
      }
    ]
  },
  {
    "database": "mydb",
    "links": [
      {
        "label": "hello",
        "app": "todo"
      },
      {
        "label": "foo",
        "app": "bar"
      }
    ]
  }
]
```

2023-10-02 21:25 UTC, kate-goldenring commented
@itowlson I noticed that in `spin templates list`, we [hide the optionality of json output format](https://github.com/fermyon/spin/blob/0306346e554a8ae2968861ee85d4c6fb6b336e8b/src/commands/templates.rs#L448). Is there a reason for that -- and one that is related to whether it should be hidden here too?

2023-10-02 21:59 UTC, itowlson commented
@kate-goldenring Just to reduce clutter in the help text.  In that case, the JSON is primarily expected to be consumed by other programs, not be interactive users, so I felt it was not worth making interactive users look at the flag.

2023-10-02 22:42 UTC, itowlson requested changes
Looks good (style nit aside) but I think it needs to either respect the `--app` filter or (less desirably) be incompatible with it.

2023-10-02 22:42 UTC, itowlson commented on src/commands/sqlite.rs
> +        if matches!(self.format, ListFormat::Json) {
This seems to ignore the `--app` filter.

2023-10-02 22:42 UTC, itowlson commented on src/commands/sqlite.rs
> +
This function is starting to feel a bit long to me (subjective I know).  How would you feel about breaking from line 227 on into something like

```
match self.format {
  ListFormat::Table => self.print_table(databases),
  ListFormat::Json => self.print_json(databases),
}
```

i.e. move all the print functionality into dedicated format-specific functions?

2023-10-03 16:45 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +        if matches!(self.format, ListFormat::Json) {
I added filtering by app, but it is slightly different than the table format in that it filters to only show databases that are linked to that app but still shows all the links, since it feels strange to misrepresent the links of a database. For example:
```sh
$ spin cloud sqlite list --format json
[
  {
    "database": "brilliant-kangaroo",
    "links": [
      {
        "label": "default",
        "app": "todo"
      }
    ]
  },
  {
    "database": "mydb",
    "links": [
      {
        "label": "hello",
        "app": "bar"
      },
      {
        "label": "foo",
        "app": "todo"
      }
    ]
  }
]
$ spin cloud sqlite list --format json --app "bar"
[
  {
    "database": "mydb",
    "links": [
      {
        "label": "hello",
        "app": "bar"
      },
      {
        "label": "foo",
        "app": "todo"
      }
    ]
  }
]
```

2023-10-03 16:46 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +
good idea. Moved it out

2023-10-03 19:17 UTC, itowlson commented on src/commands/sqlite.rs
> +        if matches!(self.format, ListFormat::Json) {
Yeah it's not quite clear what "app" filtering should mean when this has a strictly hierarchical view grouped on database.  I guess consumers can always get the unfiltered JSON and apply whatever filtering logic fits their use case.

2023-10-03 19:19 UTC, itowlson commented on src/commands/sqlite.rs
> +    /// Grouping strategy of list
Apologies, I missed the `group_by` option in my previous review.  How should this interact with the JSON representation?

2023-10-03 20:11 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +    /// Grouping strategy of list
I think of this as the "grouping strategy of a list in a table" and dont think it should apply to the json output. Would it be worth updating the comment or renaming it to `table_group_by`. Or we could re-evaluate whether we should include this `group_by` and instead just enable app based output with optional filtering.

2023-10-03 20:27 UTC, itowlson commented on src/commands/sqlite.rs
> +    /// Grouping strategy of list
I don't think it needs renaming, but if it doesn't work with JSON then I think we should have a check up front that says "you can't use grouping with JSON" rather than simply ignoring it - what do you reckon?

2023-10-03 22:02 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +    /// Grouping strategy of list
I updated it to no longer take a default value via the CLI even though a default is assumed when table is selected. this feels a little messy but i updated the command descriptions to hopefully clarify this a little

2023-10-03 22:15 UTC, itowlson approved these changes
🎉  Looks good!

2023-10-04 08:59 UTC, rylev reviewed
Seems fine though there does seem to be unnecessary code duplication between the json and table formatting code paths.

2023-10-04 08:59 UTC, rylev commented on src/commands/sqlite.rs
>          match self.group_by {
nit: to avoid duplication and make it more obvious that `GroupBy::App` is the default can this become `self.group_by.unwrap_or_default()` (where we mark `App` as the default for `GroupBy`)?

2023-10-04 08:59 UTC, rylev commented on src/commands/sqlite.rs
> +        }
Seems we're repeating a lot of the same logic here between json and table printing. Why not delay the formatting decision until we've munged all the data?

2023-10-04 08:59 UTC, rylev commented on src/commands/sqlite.rs
> +struct SimplifiedResourceLabel {
nit: maybe the name should highlight it's used for json output more than it's simplified?
```suggestion
struct ResourceLabelJson {
```

2023-10-04 08:59 UTC, rylev commented on src/commands/sqlite.rs
> +}
Nit: there shouldn't be a need to have owned strings here:
```suggestion
#[derive(Serialize)]
struct DatabasesListJson<'a> {
    database: &'a str,
    links: Vec<SimplifiedResourceLabel<'a>>,
}
```

Such a change would require you also change this:

```rust
fn json_list_format<'a>(database: &'a Database) -> DatabasesListJson<'a> {
```

2023-10-04 17:10 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +        }
One is iterating over `Links` while the other is over `Databases` since the tabular form does one row per link while the json form does one array entry per database. If we want to do links as teh output format for json, we could share code but i think it makes more sense in json to represent a database and then nest all its links

2023-10-04 17:25 UTC, kate-goldenring commented on src/commands/sqlite.rs
>          match self.group_by {
Great simplification! Thank you

2023-10-04 19:18 UTC, merged