Create default database during deploys
fermyon/cloud-plugin pull request #46
Opened 2023-07-19 14:43 UTC by kate-goldenring

Looks at an apps' requested `sqlite_databases` and creates a default database for the app if one does not exist.

2023-07-20 22:28 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +                // TODO: Fail if apps exist that are currently using a database
@rylev I realized we do not have the ability to do this currently in the plugin with the apis that we have.

2023-07-20 23:07 UTC, itowlson requested changes

2023-07-20 23:07 UTC, itowlson commented on src/commands/sqlite.rs
> +    print_databases(list);
This may be a matter for a future refactor, but I would split _getting_ the list from _printing_ the list.  (The reason being that print formats may change independently of the list API, e.g. JSON.  Though that is a future matter for sure.)

2023-07-21 01:57 UTC, kate-goldenring commented on src/commands/deploy.rs
> +                    uses_default_db(&cfg) && prompt_create_database(SPIN_DEFAULT_DATABASE)?;
In my head, i don't want to magically create a resource they could be charged for (per resource -- i am not sure about the payment model we will have in the future) without getting confirmation from them. For private preview, i am happy to just print a "Creating default database for app", though

2023-07-21 02:03 UTC, kate-goldenring commented on src/commands/deploy.rs
> +            .find(|db: &&String| *db != SPIN_DEFAULT_DATABASE)
certainly is not -- i must have double clicked it and vscode magicked it to existence

2023-07-21 02:04 UTC, itowlson commented on src/commands/deploy.rs
> +                    uses_default_db(&cfg) && prompt_create_database(SPIN_DEFAULT_DATABASE)?;
That makes sense.  But I am dubious about continuing with deployment if they decline to create the database.

2023-07-21 02:10 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +    print_databases(list);
Fair. This function is not really necessary. I moved it into the command match statement

2023-07-21 02:10 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +        println!("Invalid confirmation. Will not delete database.");
Ooph i pushed this up prematurely. Fixed

2023-07-21 02:11 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +pub struct DeleteCommand {
I'd say so, especially for programatic environments as you mentioned

2023-07-21 02:11 UTC, kate-goldenring commented on src/commands/deploy.rs
> +    Confirm::new().with_prompt(prompt).interact()
I removed the creation prompt

2023-07-21 02:13 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +                // TODO: Fail if apps exist that are currently using a database
Which we currently don't have API support to do, so we will either need to add the ability from Gluon to list apps that are correlated with databases or not prevent this for private preview

2023-07-21 02:48 UTC, itowlson approved these changes
Looks good!  I suggested some minor things but nothing blocking

2023-07-21 02:48 UTC, itowlson commented on src/commands/sqlite.rs
> +                let list: Vec<cloud_openapi::models::Database> =
Might not need the type annotation here?

2023-07-21 02:48 UTC, itowlson commented on src/commands/sqlite.rs
> +    /// Name of database to create
```suggestion
    /// Name of database to delete
```

2023-07-21 02:48 UTC, itowlson commented on src/commands/sqlite.rs
> +                        .with_context(|| format!("Problem deleting database {}", cmd.name))?;
Consider a success notification after this?  (since the prompt function prints a starting notification)

2023-07-21 02:51 UTC, kate-goldenring commented on src/commands/sqlite.rs
> +                let list: Vec<cloud_openapi::models::Database> =
ugh idk why vscode is being so specific with me today. I shall remove

2023-07-21 03:29 UTC, merged