add cloud logs command
fermyon/cloud-plugin pull request #58
Opened 2023-08-11 07:55 UTC by rajatjindal

```
spin-cloud-logs 0.1.2 (b977558 2023-08-11)
Logs fetches app logs from Fermyon Cloud

USAGE:
    spin cloud logs [OPTIONS] --app-name <app-name>

OPTIONS:
        --app-name <app-name>
            App name

        --environment-name <environment-name>
            Find app to fetch logs for in the Fermyon instance saved under the specified name. If
            omitted, Spin looks for app in default unnamed instance [env:
            FERMYON_DEPLOYMENT_ENVIRONMENT=]

        --follow
            Follow logs output

    -h, --help
            Print help information

        --interval <interval>
            interval in secs to refresh logs from cloud [default: 5]

        --tail <tail>
            Number of lines to show from the end of the logs [default: 10]

    -V, --version
            Print version information

```

2023-08-11 11:52 UTC, rylev requested changes
I'd like to figure out if there's a way to do this without repeatedly downloading *all* logs.

2023-08-11 11:52 UTC, rylev commented on src/commands/logs.rs
> +    async fn tail_logs(self, login_connection: LoginConnection, app_name: String) -> Result<()> {
Nit:
```suggestion
    async fn tail_logs(self, login_connection: LoginConnection, app_name: &str) -> Result<()> {
```

2023-08-11 11:52 UTC, rylev commented on src/commands/logs.rs
> +        let app_name: String = self.app_name.clone();
The change below means that you don't need to clone.
```suggestion
```

2023-08-11 11:52 UTC, rylev commented on src/commands/logs.rs
> +    Ok(count)
```suggestion
    fetch_and_print_lastn_logs(client, channel_id, count- printed_so_far).await
```

2023-08-11 11:52 UTC, rylev commented on src/commands/logs.rs
> +fn print_lastn_logs(logs: Vec<String>, n: usize) {
Nit: it's usually best practice to not take ownership if you don't need it. 
```suggestion
fn print_lastn_logs(logs: &[String], n: usize) {
```

2023-08-11 11:52 UTC, rylev commented on src/commands/mod.rs
> +async fn get_channel_id_cloud(
Should helpers like this live in the cloud crate?

2023-08-11 11:52 UTC, rylev commented on src/commands/logs.rs
> +            get_channel_id_cloud(&client, SPIN_DEPLOY_CHANNEL_NAME.to_string(), app_id).await?;
The error for this talks about a channel id which the user is not going to know anything about. Do we want to use `context` or `map_err` to provide a better error message?

2023-08-11 15:12 UTC, kate-goldenring commented on src/commands/logs.rs
> +impl LogsCommand {
```suggestion
impl LogsCommand {
```

2023-08-11 15:14 UTC, kate-goldenring commented on src/commands/logs.rs
> +use crate::commands::{get_app_id_cloud, get_channel_id_cloud};
Can use helper for creating the client. See below for continued suggestion
```suggestion
use crate::commands::{get_app_id_cloud, get_channel_id_cloud, create_cloud_client};
```

2023-08-11 15:16 UTC, kate-goldenring commented on src/commands/logs.rs
> +        let app_id = get_app_id_cloud(&client, app_name.as_str()).await?;
If you create the client in `run` using `create_cloud_client`, you can pass it and simplify this
```suggestion
    async fn tail_logs(self, client: &CloudClient, app_name: String) -> Result<()> {
        let app_id = get_app_id_cloud(client, app_name.as_str()).await?;
```

2023-08-11 15:42 UTC, kate-goldenring commented on src/commands/logs.rs
> +}
I believe that this needs to be changes to take the last n and keep the direction of ordering. I was thinking through this in this playground https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=efb52801edab3b4baa36ea2e68499d96
```suggestion
fn print_lastn_logs(logs: Vec<String>, n: usize) {
    for log in &logs[logs.len()-n..] {
        println!("{}", log)
    }
}
```

2023-08-11 15:51 UTC, kate-goldenring commented on src/commands/mod.rs
> +async fn get_channel_id_cloud(
yeah this sounds ideal. maybe we put up an issue for this and clean this up in a subsequent pr?

2023-08-28 02:40 UTC, rajatjindal commented on src/commands/logs.rs
> +    pub interval_secs: u64,
i was hoping there is something in built by clap for this? for now I've added a validate_args function

2023-08-28 02:42 UTC, rajatjindal commented on src/commands/logs.rs
> +    async fn tail_logs(self, login_connection: LoginConnection, app_name: String) -> Result<()> {
done

2023-08-28 02:45 UTC, rajatjindal commented on src/commands/logs.rs
> +        let app_name: String = self.app_name.clone();
hmm, I had to clone still. without that i am getting a `move` error

2023-08-28 02:45 UTC, rajatjindal commented on src/commands/logs.rs
> +    Ok(count)
hm, why do you think we need this change?

2023-08-28 02:46 UTC, rajatjindal commented on src/commands/logs.rs
> +fn print_lastn_logs(logs: Vec<String>, n: usize) {
👍 done

2023-08-28 02:48 UTC, rajatjindal commented on src/commands/mod.rs
> +async fn get_channel_id_cloud(
👍 https://github.com/fermyon/cloud-plugin/issues/73

2023-08-28 02:50 UTC, rajatjindal commented on src/commands/logs.rs
> +            get_channel_id_cloud(&client, SPIN_DEPLOY_CHANNEL_NAME.to_string(), app_id).await?;
sounds good. could you please help me come up with a msg here:

`error while finding internal handle to logs`
`internal error, current channel for the app not found`
`internal identifier for cloud app not found`

2023-08-28 02:52 UTC, rajatjindal commented
> Thanks for adding this Rajat! To @rylev's point, instead of getting all logs, can you update `channel_logs` to take in `max` aka count. The [`api_channels_id_logs_get`](https://github.com/fermyon/cloud-plugin/blob/643ceaca9a79ec334a93639079236ffc44f018f3/crates/cloud/src/client.rs#L289) already has support for requesting n many logs and it is the [latest n returned by journal](https://github.com/fermyon/journal/blob/c9fabef3f25331510e8152094b13cfe0339b818a/journal-api/journal/v1/journal.proto#L35).

I want to do that too. but lets say we start the tail command and fetched 100 lines of logs. now the app added 5 new line of logs. when we ask for 100 lines of logs again, how do we know that the last 5 are the latest ones to display?

2023-08-28 05:24 UTC, rajatjindal commented on src/commands/logs.rs
> +use crate::commands::{get_app_id_cloud, get_channel_id_cloud};
👍

2023-08-28 05:24 UTC, rajatjindal commented on src/commands/logs.rs
> +        let app_name: String = self.app_name.clone();
👍

2023-08-28 05:25 UTC, rajatjindal commented on src/commands/logs.rs
> +        let app_id = get_app_id_cloud(&client, app_name.as_str()).await?;
👍  great catch. thank you.

2023-08-28 05:51 UTC, rajatjindal commented on src/commands/logs.rs
> +}
🎉  thank you.

2023-08-28 07:10 UTC, rajatjindal commented
> > Thanks for adding this Rajat! To @rylev's point, instead of getting all logs, can you update `channel_logs` to take in `max` aka count. The [`api_channels_id_logs_get`](https://github.com/fermyon/cloud-plugin/blob/643ceaca9a79ec334a93639079236ffc44f018f3/crates/cloud/src/client.rs#L289) already has support for requesting n many logs and it is the [latest n returned by journal](https://github.com/fermyon/journal/blob/c9fabef3f25331510e8152094b13cfe0339b818a/journal-api/journal/v1/journal.proto#L35).
> 
> I want to do that too. but lets say we start the tail command and fetched 100 lines of logs. now the app added 5 new line of logs. when we ask for 100 lines of logs again, how do we know that the last 5 are the latest ones to display?

I looked at the logging api code. if we can add ability to say "give me logs since <timestamp>", then we might be able to circumvent the problem. I'll give that a try soon.

cc @michelleN - I know you were looking at the logging api as well.

2023-10-02 06:38 UTC, rajatjindal commented
this will fix #107

2023-10-17 06:47 UTC, rajatjindal commented on src/commands/logs.rs
> +    Ok(count)
this is outdated code.

2023-10-17 11:42 UTC, karthik2804 commented on src/commands/logs.rs
> +    pub app_name: String,
To be consistent with other cases we probably do not want to have an argument (eg) 'apps info' and `apps delete` commands. This would change to 

```bash
spin cloud logs <APP_NAME>
```

```suggestion
    pub app_name: String,
```

2023-10-17 18:30 UTC, itowlson commented on src/commands/logs.rs
> +    pub app_name: String,
If this is the same as the app name in `spin cloud link` and `spin cloud variables` then it should be `#[clap(short = 'a', long = "app")]` (actually we are not 100% consistent about having a `short` form but the long form is always "app").

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +    async fn logs(self, client: CloudClient, app_name: &str) -> Result<()> {
Not quite sure why you pass `app_name` separately here when it's the same as `self.app_name`?

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +            .map_err(|_e| anyhow!("app with name {:?} not found", app_name))?
This seems to lump all errors into the "app not found" case, which would point diagnosis in the wrong direction when the app _does_ exist but there's some other problem.  Consider propagating the original error with context, or at least logging it.

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +    client: &CloudClient,
```suggestion
    client: &impl CloudClientInterface,
```

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +    interval: u64,
This should be a Duration by this point.

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +    client: &CloudClient,
```suggestion
    client: &impl CloudClientInterface,
```

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +        .channel_logs_raw(channel_id.to_string(), max_lines, Some(since.to_string()))
I guess this is out of scope for this PR but it's weird that we get the channel ID as a Uuid and then have to convert it back to a String to use it.  It would be nice to treat it _always_ as a Uuid.

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +    let mut new_since = Utc::now().sub(since).to_rfc3339();
`new` here is a bit of a wart - when you're going round the loop the it's not necessarily "new" any more.  I don't love shadowing but maybe plain "since" would be clearer?

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +            fetch_logs_and_print_once(client, channel_id, None, new_since.to_owned()).await?;
Is it necessary to keep calling `to_owned()` on what is already a `String`?

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +        for line in entry.log_lines.as_ref().unwrap() {
Comment why these unwraps are safe

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +        return Err(anyhow!("invalid duration"));
This will be displayed to a user who saw nothing wrong with "3min" or "1h30m".  Help them understand what the command accepts as "valid".

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +    /// interval in secs to refresh logs from cloud
Consistent capitalisation
```suggestion
    /// Interval in secs to refresh logs from cloud
```

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +    /// fetch logs since
If I read this as a doc string I would think I should enter a date or time.  "Fetch logs since 2:30."  Provide guidance e.g.
```suggestion
    /// How long ago to fetch logs from, expressed as a duration. The duration format
    /// is a number and a unit, where the unit is 's' for seconds, 'm' for minutes, 'h' for hours
    /// or 'd' for days (e.g. "30m" for 30 minutes ago).  The default it 7 days.
```

(The start of that suggestion feels a bit too wordy and indirect, but hopefully gives an idea of the kind of thing.)

2023-10-17 19:31 UTC, itowlson commented on src/commands/logs.rs
> +fn parse_duration(arg: &str) -> Result<std::time::Duration, anyhow::Error> {
tiny nit: I find this form more concise:

```suggestion
fn parse_duration(arg: &str) -> anyhow::Result<std::time::Duration> {
```

2023-10-18 01:20 UTC, rajatjindal commented on src/commands/logs.rs
> +    async fn logs(self, client: CloudClient, app_name: &str) -> Result<()> {
in one of the iteration i was running into move error IIRC. changed it to use app_name from self.

2023-10-18 01:33 UTC, rajatjindal commented on src/commands/logs.rs
> +            .map_err(|_e| anyhow!("app with name {:?} not found", app_name))?
done.

2023-10-18 01:42 UTC, rajatjindal commented on src/commands/logs.rs
> +        return Err(anyhow!("invalid duration"));
```
cloud-plugin logs --app-name non-exist --since 30min
error: Invalid value "30min" for '--since <since>': supported formats are "300s", "5m", "4h" or "1d". formats such as "1h30m" or "30min" are not supported
```

is this looking ok now?

2023-10-18 02:01 UTC, itowlson commented on src/commands/logs.rs
> +        return Err(anyhow!("invalid duration"));
I'd drop the "formats such as "1h30m" or "30min" are not supported" - you've told them what _is_ supported and that's probably all that's needed.  We can always expand the error if people do try combining units but simple will do to start with.  Thanks!

2023-10-18 02:36 UTC, rajatjindal commented on src/commands/logs.rs
> +    /// fetch logs since
```
Only return logs newer than a relative duration.
```

2023-10-18 02:41 UTC, rajatjindal commented on src/commands/logs.rs
> +    interval: u64,
actually `interval` is different from `since`.  

interval is the time in seconds after which request is made to server to fetch latest logs. This is required as our logs api don't support streaming right now.

2023-10-18 02:46 UTC, rajatjindal commented on src/commands/logs.rs
> +    pub app_name: String,
thanks. renamed variable to `app` and changed it to be an argument instead of flag

2023-10-18 02:53 UTC, itowlson commented on src/commands/logs.rs
> +    interval: u64,
I know interval is different from since, but it's still a Duration.  In the same way as you get `since` out of a string and into a Duration before getting into the core operation, it would be good to get `interval` out of a `u64` and into a Duration too.  That avoids any uncertainty about the semantics of the u64.

2023-10-18 02:56 UTC, rajatjindal commented on src/commands/logs.rs
> +        return Err(anyhow!("invalid duration"));
done.

2023-10-18 03:01 UTC, rajatjindal commented on src/commands/logs.rs
> +    interval: u64,
👍  done. thanks Ivan. (just wanted to make sure the distinction between interval and since was clear in this context).

2023-10-18 03:08 UTC, rajatjindal commented on src/commands/logs.rs
> +        .channel_logs_raw(channel_id.to_string(), max_lines, Some(since.to_string()))
yeah, all functions in client currently use string. I guess the generated client will need some tweaking for this.

2023-10-18 03:11 UTC, rajatjindal commented on src/commands/logs.rs
> +    let mut new_since = Utc::now().sub(since).to_rfc3339();
just to be clear, when we are going in the loop, new_since is updated after each loop iteration (to the last log timestamp), so it is indeed new_since. I can change it to since if you still think that would be better?

2023-10-18 03:13 UTC, rajatjindal commented on src/commands/logs.rs
> +            fetch_logs_and_print_once(client, channel_id, None, new_since.to_owned()).await?;
I think one of the previous comment had me remove `app_name` passed along as parameter. Before that change, we were getting a moved error with this. which is now no longer the case 🎉  thank you Ivan.

2023-10-18 03:15 UTC, itowlson commented on src/commands/logs.rs
> +    let mut new_since = Utc::now().sub(since).to_rfc3339();
I can't muster strong feelings about it  _grin_ - feel free to leave it as is.

2023-10-18 04:18 UTC, rajatjindal commented on src/commands/logs.rs
> +        let app_name: String = self.app_name.clone();
fixed now

2023-10-18 13:14 UTC, kate-goldenring reviewed
Thanks for updating the APIs to make this possible @rajatjindal

2023-10-18 13:14 UTC, kate-goldenring commented on src/commands/logs.rs
> +            r#"supported formats are "300s", "5m", "4h" or "1d""#
```suggestion
            r#"time format must be a number followed by an allowed unit ("300s", "5m", "4h" or "1d")"#
```

2023-10-18 13:14 UTC, kate-goldenring commented on src/commands/logs.rs
> +            .map_err(|e| anyhow!("app with name {:?} not found\n\n{:?}", &self.app, e))?
Why the new lines here on the error? There aren't new lines on the next identical error. Can we be consistent?

2023-10-18 13:14 UTC, kate-goldenring commented on src/commands/logs.rs
> +    let mut new_since = Utc::now().sub(since).to_rfc3339();
The `new` also caught me off guard. I think `curr_since` would be better.

2023-10-18 13:14 UTC, kate-goldenring commented on src/commands/logs.rs
> +            println!("{}", line.line.as_ref().unwrap());
Can we prefix the log time here? It would be helpful to know the time of each log and make it easier to tell it is a log. For example, my logs for an app are the following which made me think the log command was erroring at first
```sh
Kates-MBP :: ~/Programs/cloud-plugin 2 » cargo run -- logs --since 10d boo-todo
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/cloud-plugin logs --since 10d boo-todo`
Cannot find file /favicon.ico. Attempting fallback.
Cannot read file: cannot open /favicon.ico

Caused by:
    No such file or directory (os error 44)
```

2023-10-23 04:23 UTC, rajatjindal commented on src/commands/logs.rs
> +    /// Find app to fetch logs for in the Fermyon instance saved under the specified name.
this is indeed for `deployment_env_id`. copied (and modified) from `deploy.rs` file

2023-10-23 04:23 UTC, rajatjindal commented on src/commands/logs.rs
> +            r#"supported formats are "300s", "5m", "4h" or "1d""#
thank you

2023-10-23 04:26 UTC, rajatjindal commented on src/commands/logs.rs
> +            .map_err(|e| anyhow!("app with name {:?} not found\n\n{:?}", &self.app, e))?
usually I try to follow pattern from existing code :) : https://github.com/fermyon/cloud-plugin/blob/d410545f4a62c81b911c33e49658cec30873be29/src/commands/deploy.rs#L125 

in this case, I copied this from `deploy.rs`. I am happy to change it to the recommended pattern.

2023-10-23 04:29 UTC, rajatjindal commented on src/commands/logs.rs
> +            println!("{}", line.line.as_ref().unwrap());
I think we should add a flag to print timestamps with log line. e.g. there are instances where people have timestamps in their logs already, and duplicate timestamps won't look nice either.

if we agree to a flag, next question would be the default value. I don't have strong feelings about that. but I think we can show timestamps by default?

2023-10-23 06:19 UTC, rajatjindal commented on src/commands/logs.rs
> +        };
getting error with change:

```
   Compiling cloud-plugin v0.4.0 (/Users/rajatjindal/go/src/github.com/fermyon/cloud-plugin)
error: expected one of `.`, `?`, `{`, or an operator, found `;`
  --> src/commands/logs.rs:64:87
   |
60 |         let app_id = match client
   |                      -----
   |                      |
   |                      while parsing this `match` expression
   |                      help: try removing this `match`
...
64 |             .map_err(|e| anyhow!("error finding app with name {:?}: {e}", &self.app))?;
   |                                                                                       ^ expected one of `.`, `?`, `{`, or an operator


```

tried removing `match`

```
   Compiling cloud-plugin v0.4.0 (/Users/rajatjindal/go/src/github.com/fermyon/cloud-plugin)
error[E0599]: no method named `map_err` found for enum `std::option::Option` in the current scope
  --> src/commands/logs.rs:64:14
   |
60 |           let app_id = client
   |  ______________________-
61 | |             .get_app_id(&self.app)
62 | |             .await
63 | |             .with_context(|| format!("app with name {:?} not found", &self.app))?
64 | |             .map_err(|e| anyhow!("error finding app with name {:?}: {e}", &self.app))?;
   | |             -^^^^^^^ help: there is a method with a similar name: `map_or`
```

2023-10-23 06:27 UTC, rajatjindal commented on src/commands/logs.rs
> +        return Err(anyhow!("interval cannot be less than 2 seconds"));
done

2023-10-23 10:14 UTC, rajatjindal commented on src/commands/logs.rs
> +    let mut new_since = Utc::now().sub(since).to_rfc3339();
👍 , changing it to 'curr_since'

2023-10-23 10:25 UTC, rajatjindal commented on src/commands/logs.rs
> +        for line in entry.log_lines.as_ref().unwrap() {
i completely did. added a if condition to check if this is defined. and changed the log_line to default to "" if its None

2023-10-23 19:39 UTC, itowlson commented on src/commands/logs.rs
> +            .map_err(|e| anyhow!("app with name {:?} not found\n\n{:?}", &self.app, e))?
@rajatjindal that's specifically for the program-exit appending the cloud FAQ link on all deploy failures.  I don't think we generally split out underlying errors onto separate lines explicitly (though `context/with_context` render the "stack" of causes one per line).

2023-10-23 19:43 UTC, itowlson commented on src/commands/logs.rs
> +    /// Find app to fetch logs for in the Fermyon instance saved under the specified name.
The ambiguity arises in this case between "app saved under the specified name" vs "Fermyon instance saved under the specified name" (which doesn't arise in deploy, though I'm sure we could clarify the wording there too!).  How about:

```suggestion
    /// Use the Fermyon instance saved under the specified name.
```

2023-10-23 19:55 UTC, itowlson commented on src/commands/logs.rs
> +            println!("{}", line.line.as_ref().unwrap());
The Cloud UI defaults to showing timestamps.  We may be better off following the download format than the UI though, as the UI uses a non-sortable timestamp format, and uses client local time.  (The download format uses sortable UTC time; the disadvantage is that the timestamps get long.)

2023-10-25 09:19 UTC, rajatjindal commented on src/commands/logs.rs
> +            // line will always have some content, so it is safe to unwrap
I have restructured this code a bit. happy to make further changes if there is a different rust idomatic way of doing this.

2023-10-25 12:58 UTC, rylev commented on src/commands/logs.rs
> +        };
Sorry - this is why I shouldn't try to write Rust without a compiler. Removing the `match` is right. It seems you switched the `with_context` and `map_err` lines. If you switch those back, does it work?

2023-10-25 14:18 UTC, rajatjindal commented on src/commands/logs.rs
> +        for line in entry.log_lines.as_ref().unwrap() {
i have restructured this function a bit to check for None etc.

2023-10-25 15:10 UTC, rajatjindal commented on src/commands/logs.rs
> +        };
Ryan helped me fix it. done

2023-10-25 15:18 UTC, rajatjindal commented on src/main.rs
> +    /// Fetch app logs from Fermyon Cloud
done. thanks Kate

2023-10-26 01:33 UTC, rajatjindal commented
@kate-goldenring @rylev @itowlson @karthik2804 

thank you for your feedback on this PR. I think this is now ready to be merged. please let me know if there are comments that I might have missed to address. 

thanks

2023-10-26 01:42 UTC, itowlson commented on src/commands/logs.rs
> +    /// Find app to fetch logs for in the Fermyon instance saved under the specified name.
@rajatjindal this seems to be marked as resolved without any change being made - is there a push pending?

2023-10-26 02:03 UTC, itowlson reviewed
I don't think anything I have is blocking (though it would be _highly_ desirable to get rid of that panic), but I don't feel I know enough to approve, sorry.

2023-10-26 02:03 UTC, itowlson commented on src/commands/logs.rs
> +                None => panic!("timestamp is None for the log entry"),
This is not panic-worthy.

2023-10-26 04:23 UTC, rajatjindal commented on src/commands/logs.rs
> +        self.logs(&client).await.map_err(|e| anyhow!("{:?}", e))
👍 make sense. removed

2023-10-26 04:26 UTC, rajatjindal commented on src/commands/logs.rs
> +    max_lines: Option<i32>,
down the line we need to pass None (when following logs). I have changed it to be `i32` until the function call where that is required

2023-10-26 04:30 UTC, rajatjindal commented on src/commands/logs.rs
> +fn print_lastn_logs(entries: &[Entry], show_timestamp: bool) -> Option<&str> {
done

2023-10-26 04:32 UTC, rajatjindal commented on src/commands/logs.rs
> +                None => panic!("timestamp is None for the log entry"),
changed it to do nothing.

2023-10-26 04:33 UTC, rajatjindal commented
@itowlson, as always, thank you for your insightful feedback on this PR.

2023-10-26 04:56 UTC, itowlson commented on src/commands/logs.rs
> +    /// Find app to fetch logs for in the Fermyon instance saved under the specified name.
@rajatjindal forgive me for nagging on this but I would strongly encourage changing this to something generic like 

```suggestion
    /// Use the Fermyon instance saved under the specified name.
```

The mention of "app" makes it sound like the app, a la "find the app blah blah the specified name"

2023-10-26 04:58 UTC, itowlson commented on src/commands/logs.rs
> +                None => panic!("timestamp is None for the log entry"),
Should it do nothing or record the log text without the timestamp?  (I don't know the correct behaviour: if "do nothing" is right then all good!)

2023-10-26 04:59 UTC, itowlson commented
Looking good @rajatjindal, just one question and one thing that I mentioned in a comment but forgot to log in the review - sorry about that!

2023-10-26 05:13 UTC, rajatjindal commented on src/commands/logs.rs
> +    /// Find app to fetch logs for in the Fermyon instance saved under the specified name.
thank you for being persistent. I had intended to address this feedback, but it seems like it got lost in other comments while i was going through the comments.

2023-10-26 05:40 UTC, rajatjindal commented on src/commands/logs.rs
> +                None => panic!("timestamp is None for the log entry"),
if we do print log text here without updating `since`, then we may endup in a situation where this particular line can keep printing again and again (until we get a valid entry which endup updating `since`). 

my intution is that if api returned a valid entry, it will always have both text and time, so in this case, we can ignore the log text.

2023-10-27 17:17 UTC, bacongobbler commented
Would you mind changing this to use the /api/apps/:id/logs endpoints? The latest version of the cloud-openapi client contains these endpoints. The channel log endpoints are planned to be deprecated soon.

2023-10-30 11:46 UTC, rajatjindal commented
I have update openapi client and updated the PR to use new endpoints.

2023-10-30 12:16 UTC, radu-matei approved these changes
Tested this end to end and everything looks great!

LGTM

2023-10-30 15:12 UTC, bacongobbler approved these changes

2023-10-30 16:06 UTC, rylev approved these changes
Just some last second code nits. Feel free to merge this without addressing those!

2023-10-30 16:06 UTC, rylev commented on src/commands/logs.rs
> +            }
```suggestion
            if let Some(time) =  &log_entry.time {
                    if show_timestamp {
                        println!("[{time}] {log}");
                    } else {
                        println!("{log}");
                    }

                    since = Some(time.as_str());
            }
```

2023-10-30 16:06 UTC, rylev commented on src/commands/logs.rs
> +            };
```suggestion
        for log_entry in log_lines.iter().filter_map(|l| l.line.as_ref()) {
```

2023-10-30 16:06 UTC, rylev commented on src/commands/logs.rs
> +        };
```suggestion
    for entry in entries.iter().rev().filter_map(|e| e.long_lines.as_ref()) {
```

2023-10-30 16:18 UTC, kate-goldenring approved these changes
LGTM! Thanks @rajatjindal

2023-10-31 08:08 UTC, rajatjindal commented on src/commands/logs.rs
> +            };
i tried this and ran into a problem (needed to use filter instead of filter_map). tried spending sometime to fix that, but the code seemed more readable in current form. so going to skip this one for now

2023-10-31 08:09 UTC, rajatjindal commented on src/commands/logs.rs
> +        };
i tried this and ran into a problem (needed to use filter instead of filter_map). tried spending sometime to fix that, but the code seemed more readable in current form. so going to skip this one for now

2023-10-31 08:45 UTC, merged