add apps subcommand that allows to list and delete apps
fermyon/cloud-plugin pull request #67
Opened 2023-08-18 20:17 UTC by karthik2804

This PR adds a new top-level command `apps` that further has `list` and `delete` subcommands. 

fixes #9
fixes #40

2023-08-18 20:19 UTC, karthik2804 commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
This just fetches the first 50 apps by default. I am not sure what the UX for this should be. Do we want to follow the behavior of something like `ls` and print the entire list?

2023-08-18 20:43 UTC, kate-goldenring commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
For others to reference, default is set in [Nimbus here](https://github.com/fermyon/nimbus/blob/main/src/Api/Controllers/AppsController.cs#L44-L45). 
Maybe provide an `--all` flag that will cause all to be printed. This would require making a `list_all_apps` fn that will make `total_items` / 50 calls.

2023-08-18 20:43 UTC, kate-goldenring commented on src/commands/apps.rs
> +                let app_list: Vec<&str> = app_list_page
You can consume the `app_list_page` object here. (sorry suggestion wasn't working)
```sh
 let app_list: Vec<String> = app_list_page
                    .items
                    .into_iter()
                    .map(|app_item| app_item.name)
                    .collect();
```

2023-08-18 20:43 UTC, kate-goldenring commented on src/commands/mod.rs
> +        .await
I think most of the functions in `mod` we are hoping to move to the `cloud` crate. I don't think this one is powerful enough to move there and for that reason i would say we should keep this in `variables.rs` and just use the two lines in `apps.rs`

2023-08-18 20:45 UTC, kate-goldenring commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
But I think something like this would be nice, which has a header and a total count and then just line by line like you have
```sh
spin cloud apps list
Apps (3)
foo
bar
fee
```

2023-08-18 20:47 UTC, karthik2804 commented on src/commands/mod.rs
> +        .await
I think the function will be potentially used multiple times within `apps.rs` in case we add commands to get information about one particular app. something along the lines of 

```
spin cloud apps details my-app
```

2023-08-18 21:31 UTC, karthik2804 commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
Would be a bad idea to change the `page_size` to the size of `total_items` which would help us avoid making multiple calls?

2023-08-18 21:43 UTC, karthik2804 commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
On second thought - it would not make much of a big difference as the current maximum limit is 100 and that would be 2 requests regardless if there are over 50 apps.

2023-08-20 21:40 UTC, itowlson commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
It would be surprising if `--all` wasn't the default.

We already did this for channels and revisions (https://github.com/fermyon/spin/pull/973) and it was pretty simple - presumably apps would be very much the same?

@kate-goldenring The initial line could be a pain for piping e.g. `spin cloud apps list | sort`.

2023-08-20 22:02 UTC, itowlson commented on src/commands/apps.rs
> +                    (true, _) | (false, true) => println!("Apps ({})", app_list_page.total_items),
This plays merry hob with piping e.g. `spin cloud apps list | sort`

2023-08-21 15:19 UTC, karthik2804 commented on src/commands/apps.rs
> +                    (false, false) => println!("Note: Displaying the first {} of {} Apps. To list all the apps run \"spin cloud apps list -all\"", DEFAULT_APPLIST_PAGE_SIZE, app_list_page.total_items
I like making it the default option - I will add an option called count that returns the total number of apps.

2023-08-21 15:43 UTC, kate-goldenring commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
True unless you do `spin cloud apps list | tail -n +2 | sort`. We might want to standardize what to do about listed output. Should we never add a header row? When is it useful? With `sqlite` CLI sketched, we've talked about having a header.

2023-08-21 15:47 UTC, karthik2804 commented on src/commands/apps.rs
> +                    (true, _) | (false, true) => println!("Apps ({})", app_list_page.total_items),
Removed it.

2023-08-21 15:49 UTC, karthik2804 commented on src/commands/apps.rs
> +                    (false, false) => println!("Note: Displaying the first {} of {} Apps. To list all the apps run \"spin cloud apps list -all\"", DEFAULT_APPLIST_PAGE_SIZE, app_list_page.total_items
I have removed the `--all` flag - therefore this has been removed.

2023-08-21 21:37 UTC, itowlson commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
For an unhelpful comparison:

`spin plugins list` prints a bare list, no header row.

`spin templates list` prints a table with headers and separators and borders and everything.  The reason for this is to display multiple fields (name, description, installed from).

I'm not hugely sold on the usefulness of a header row that just shows the object type and a count.  I think the argument for the `sqlite` case was so the output wasn't empty if they had no databases.  But in that case it might be clearer just to print "You have no applications / databases / etc."?  (maybe to stderr instead of stdout, so that pipes could tell the cases apart)

2023-08-22 04:57 UTC, itowlson requested changes
The only blocker is the incorrect syntax for the count flag, but I think we should also make sure we have consensus on the UI e.g. whether we want to have the count flag, whether we want to have a header row, and whether we want to print anything when there are no entities.  This is important because of likely broader implications e.g. we'd probably want the `sqlite list` command to have the same behaviour.

2023-08-22 04:57 UTC, itowlson commented on src/commands/apps.rs
> +    #[clap(short = 'a', long = "all", takes_value = false)]
This syntax was for an old option

2023-08-22 04:57 UTC, itowlson commented on src/commands/apps.rs
> +    pub count: bool,
I am not convinced this is particularly useful; I'd consider taking it out, and adding it back if someone says "I want to count my apps more efficiently than list and `wc`".

In that case I give you permission to call the PR "I told you so"

2023-08-22 04:57 UTC, itowlson commented on src/commands/apps.rs
> +                        print_app_list(&app_list_page);
Consider eprintln-ing something like "You have no applications" if the count is 0.

2023-08-22 05:09 UTC, karthik2804 commented on src/commands/apps.rs
> +    pub count: bool,
Removed and noted!

2023-08-22 05:09 UTC, karthik2804 commented on src/commands/apps.rs
> +    #[clap(short = 'a', long = "all", takes_value = false)]
Removed it.

2023-08-22 05:10 UTC, karthik2804 commented on src/commands/apps.rs
> +                        print_app_list(&app_list_page);
Done!

2023-08-22 17:52 UTC, kate-goldenring commented on src/commands/apps.rs
> +                let app_list_page = client.list_apps().await?;
That's a good point about a header being improperly used to denote empty list.

2023-08-22 17:56 UTC, kate-goldenring commented on src/commands/apps.rs
> +                match app_list_page.total_items > 0 {
Curious, why did you choose to do a match statement here instead of an if statement?

2023-08-22 18:03 UTC, kate-goldenring reviewed
I think this is looking ready to switch from Draft to Ready for Review. To your comment @itowlson, I am aligned with no headers and instead output on empty as is done here.

2023-08-22 18:03 UTC, kate-goldenring commented on src/commands/apps.rs
> +                println!("Delete app named \"{}\" Successully!", &cmd.app);
```suggestion
                println!("Deleted app \"{}\" successfully.", &cmd.app);
```

2023-08-22 18:03 UTC, karthik2804 commented on src/commands/apps.rs
> +                match app_list_page.total_items > 0 {
Past reviews have trained me to prefer `match` over `if` but I do not know if it is not appropriate here.

2023-08-22 18:05 UTC, kate-goldenring commented on src/commands/apps.rs
> +                match app_list_page.total_items > 0 {
i would usually only match on a bool if it was evaluating to a result that the match was capturing. I'm curious if there is a best practice here. @itowlson any thoughts?

2023-08-22 20:15 UTC, itowlson commented on src/commands/apps.rs
> +                match app_list_page.total_items > 0 {
For a predicate like this I'd probably choose `if` because it avoids the clutter of the `true => / false =>` prefixes (but my opinion is not strong, and I am a really poor bellwether for what the Rust Gods consider best practice).

2023-08-22 20:31 UTC, itowlson approved these changes
LGTM, one non-blocking suggestion (plus the comment about if vs match which is also non-blocking)

2023-08-22 20:31 UTC, itowlson commented on src/commands/apps.rs
> +            AppsCommand::List(cmd) => {
Style suggestion: In many places we move each leaf command's `run` implementation down to that leaf command, so the intermediate level becomes (cf. https://github.com/fermyon/spin/blob/60011faf310e673f20fc7d5de20f4df8a99374e7/src/commands/plugins.rs#L43)

```
impl FieCommand {
  fn run(&self) {
    match self {
      Self::AliceCommand(cmd) => cmd.run(),
      Self::BobCommand(cmd) => cmd.run(),
    }
  }
}
```

This removes a level of structure and indentation from the actual real command logic, and keeps the implementations of the subcommands fully distinct in the source code.

It's not a must-do but it's a pattern I find significantly clearer.

2023-08-22 20:36 UTC, karthik2804 commented on src/commands/apps.rs
> +            AppsCommand::List(cmd) => {
I based it off the structure in `variables` and `sqlite`. I do not have a preference here. I am happy to go eitherway. Let me know!

2023-08-22 20:51 UTC, itowlson commented on src/commands/apps.rs
> +            AppsCommand::List(cmd) => {
Oh, if `cloud-plugin` is inlining everything then I guess be consistent.

2023-08-22 22:16 UTC, karthik2804 commented
@kate-goldenring @itowlson any strong opinions on `match` vs `if`? I am happy to go either way. I can update and then merge.

2023-08-22 22:39 UTC, itowlson commented
@karthik2804 I am Team If in this case

2023-08-23 03:59 UTC, karthik2804 commented
@itowlson Well I will take the side with Team if this time around then!

2023-08-23 04:01 UTC, itowlson commented
![image](https://github.com/fermyon/cloud-plugin/assets/865538/b1188825-c89f-444c-9d25-ea446ca42bd9)

2023-08-23 04:33 UTC, merged