Add get app subcommand to get app details
fermyon/cloud-plugin pull request #94
Opened 2023-09-19 20:30 UTC by karthik2804

This PR adds a get subcommand to apps to allow for getting details about an app. It helps with getting the Base URL of apps quickly without having to open up the cloud UI.

2023-09-19 20:51 UTC, itowlson requested changes
The blocking one is the blank Description thing; the others are merely suggestions

2023-09-19 20:51 UTC, itowlson commented on src/commands/apps.rs
> +                    app.channels[0].domain.as_ref().unwrap_or(&String::new())
If there's no URL then skip this print rather than printing `URL: https://` (I know, it's a "can't happen" situation)

2023-09-19 20:51 UTC, itowlson commented on src/commands/apps.rs
> +                    println!("Custom domain: {}", val.name);
If the custom domain is ready, wouldn't the URL already be showing it?  Alternative suggestion is to have URL be where the app is _currently_ available (whether custom domain or Fermyon custom subdomain or default deployment domain) and print an additional message _only if_ there is a custom domain pending.  That is:

* If there is no custom domain: show URL as the Fermyon URL
* If there is a custom domain and it is ready: show URL as the custom URL
* If there is a custom domain, but it is pending: show URL as the Fermyon one (the one which works!), and print an additional message along the lines of "Custom domain ... in progress / waiting to be provisioned / whatever"

2023-09-19 20:51 UTC, itowlson commented on src/commands/apps.rs
> +                println!("Description: {}", &app.description.unwrap_or_default());
If the description is empty, then skip this line rather than printing `Description:` with nothing next to it.

2023-09-19 21:29 UTC, kate-goldenring commented on src/commands/apps.rs
> +                        cloud_openapi::models::DomainValidationStatus::InProgress => "In progress",
nit: I would import `use cloud_openapi::models:DomainValidationStatus` instead of using the fully qualified path here
```suggestion
                        DomainValidationStatus::InProgress => "In progress",
```

2023-09-19 21:29 UTC, kate-goldenring commented on src/commands/apps.rs
> +    Get(GetCommand),
`Get` seems not quite the right name to me. What about `Describe` or `Info`? Maybe `Get` is right here. Is there a CLI you've seen that you're modeling after?

2023-09-19 21:35 UTC, karthik2804 commented on src/commands/apps.rs
> +    Get(GetCommand),
I was just using the HTTP method here and it looked like it was descriptive enough of "get" app info - I am open to suggestions here. 
One possibility might be `get-info`?

2023-09-19 23:01 UTC, karthik2804 commented
@itowlson I have addressed the comments.

2023-09-19 23:02 UTC, karthik2804 commented on src/commands/apps.rs
> +                        cloud_openapi::models::DomainValidationStatus::InProgress => "In progress",
Done

2023-09-19 23:25 UTC, itowlson approved these changes
LGTM subject to agreement with Kate on the command name - thanks!

2023-09-19 23:25 UTC, itowlson commented on src/commands/apps.rs
> +                                    println!("URL: https://{}", url);
wow, I let _one_ of my error messages stray into column 81, and `cargo fmt` gets mediaeval on my code with a rusty fork, but you have 9 levels of indent and it's all "right this way Mister Karthik can I escort you to the VIP zone".  THE INJUSTICE

More seriously... I am appreciating the additional refinement of the UI, but the downside is it has made this function very long and very deeply indented.  I'd strongly encourage breaking it up - ideally into command handlers, but at least pulling out some of the analysis and print logic into helpers.  It's not a blocker though.

2023-09-19 23:36 UTC, kate-goldenring commented on src/commands/apps.rs
> +    /// Get Details about a deployed app in Fermyon Cloud
nit
```suggestion
    /// Get details about a deployed app in Fermyon Cloud
```

2023-09-19 23:42 UTC, kate-goldenring commented on src/commands/apps.rs
> +    Get(GetCommand),
Why `get-info` over just `info`? Maybe we take a vote in chat? I feel like to me, the following is displaying info, and `spin cloud apps info "lottery"` feels clearer. "get" like you mention is informative to HTTP method types but IMO CLIs require another level of specificity.

```sh
$ spin cloud apps get "lottery"
Name: lottery
Description: Draw a Magic 8 Ball Winner
URL: https://workshoplottery.fermyon.app
```

2023-09-21 03:15 UTC, karthik2804 commented on src/commands/apps.rs
> +    /// Get Details about a deployed app in Fermyon Cloud
fixed

2023-09-21 03:15 UTC, karthik2804 commented
@kate-goldenring I have renamed the command to `info`.

2023-09-21 16:14 UTC, kate-goldenring approved these changes
Thanks Karthik!

2023-09-21 16:48 UTC, merged